spring:
  data:
    hbase:
      client-properties: hbase.client.retries.number=3
      kerberos:
        kerb5: D:/krb/krb5.conf
        keytab: D:/krb/hbase.keytab
        principal: hbase/kad-crm02@KAD.COM